### ISSUE TITLE
Should be able to change the replace function of a mocked function

### ISSUE THREAD

**Issue by mankins** [dwyl/aws-sdk-mock#152]
Within my tests, I'd like to be able to automatically change the value of the replace function:

```   
    AWS.mock('S3', 'getObject', 'a');

    // some time in the future
    AWS.mock('S3', 'getObject', 'b');
```

Currently the first one wins, and in this example, the value is `a` forever.

Calling `restore` between tests was not working. I created a PR that fixes this behavior and introduces the updating of mock values by calling the function again.

**Comment by nelsonic** [comment]
Hi @mankins thank you for opening this issue! 👍 
While we _totally understand_ the use case you have outlined above,
_not_ changing the value when "re-mocking" is a _feature_ some people _rely_ on.
Therefore this is a "breaking change". 
We would need to create a _new method_ to "re-mock" to _not alter_ the existing behaviour
otherwise making this change will "break" some people's code. 

If you have time, please create a `remock` method and ***`new`*** tests  to ensure "_backward compatibility_". implement the desired re-assignment functionality in the _new_ method.

Thanks!

**Comment by mankins** [comment]
Gotcha, will give it a go.

**Comment by mankins** [comment]
I just added new backwards compatible methods in #153

**Comment by mankins** [comment]
Thanks! :)
