### ISSUE TITLE
Request.on and Request.send cannot be mocked

### ISSUE THREAD

**Issue by richas32** [dwyl/aws-sdk-mock#201]
request.send and request.on were added to the request sent back from mocking services like 'TransactWrite'.  however they are empty and do nothing.  if the caller uses send instead of promise there is no way to mock this as the service.  The mock function should take an extra parameter(s) to determine if on and send should be used and the resolve should happen from the send in that case.

**Comment by michaelpinnell** [comment]
I just would like to personally bump this issue, I'm running into similar problems where the bit of code I'm trying to test uses request.send so that I can inspect the type of error I'm getting from S3 to determine if i should retry or not.  As a result when writing unit tests if I add the callback invocation dvddpl suggests my tests pass, but I'm curious why to date the send method we are mocking is empty and doesn't actually include at the very least the callback invocation.  I understand it's not a perfect solution, but I'd at least like it as an option

**Comment by nelsonic** [comment]
`aws-sdk-mock@5.3.0` on NPM contains the fix for this. 📦 Thanks again @michaelpinnell 👍
