### ISSUE TITLE
API gateway

### ISSUE THREAD

**Issue by aesopwolf** [dwyl/aws-sdk-mock#25]
Would it make sense to create a mock for the API gateway? If so, I wouldn't mind working on it.

**Comment by jruts** [comment]
Hi @aesopwolf , I do not know if I understand your question completely, but this library was created to easily mock all the methods available in the aws-sdk. Since you can interact with the API Gateway through the [aws-sdk](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html) you can already mock this today with the current aws-sdk-mock library.

I hope this is an answer to your question.

**Comment by aesopwolf** [comment]
Got it, I follow now.

I saw "SNS, DynamoDB, S3" in the README and was assuming it was limited to those three services. I was definitely reading too fast and jumped the gun when I posted this issue haha.

Thanks for your help :)
